{
 "title": "Plex Server Health",
 "tags": [ "Plex" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "plex_version",
    "label": "plex_version",
    "query": {
     "query": "label_values(server_info{version=\"$plex_version\"},version)"
    }
   },
   {
    "name": "grafana_version",
    "label": "grafana_installed_version",
    "query": {
     "query": "label_values(grafana_info{grafana_installed_version!=\"12.2.1\"},grafana_installed_version)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Build Info",
   "type": "text",
   "description": "Current build version",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "\n<div class=\"text-center\">\n <img style=\"height:80px\" src=\"https://play-lh.googleusercontent.com/F39M_Ce9OBW62qntNOq6jvUH3Nh0N-03eGNFFU14GAU-hCU0RlHBONYYBiS-0SY0kaY\">\n <h3 style=\"padding-top:15px\">$plex_version</h3>\n<div>"
   }
  },
  {
   "title": "Last Boot Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_boot_ms", "legendFormat": "Boot Time" }
   ]
  },
  {
   "title": "Stack Availability",
   "type": "stat",
   "description": "Uptime of all stack components",
   "gridPos": { "h": 15, "w": 14, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job!=\"node_exporter\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "radarr_running{job=\"node_exporter_m1\"}",
     "legendFormat": "Radarr"
    },
    {
     "expr": "sonarr_running{job=\"node_exporter_m1\"}",
     "legendFormat": "Sonarr"
    },
    {
     "expr": "plex_running{job=\"node_exporter_m1\"}",
     "legendFormat": "Plex"
    },
    { "expr": "nzbget_running", "legendFormat": "NZBGet" }
   ]
  },
  {
   "title": "Server Uptime",
   "type": "stat",
   "description": "Plex Server Uptime since the last reboot with reboot indicators",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "otel_system_uptime_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Grafana Version",
   "type": "text",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "options": {
    "content": "\n<div class=\"text-center\">\n <img style=\"height:60px\" src=\"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiOfONcteJl83Cfa5S1NkRRjbHp7SQdNqwp7MAGRFgihFFSomCZqSyNpl9LJPSfpz7_SIo0oCybb9ZubYU1TuRpBl4Jo6cAf21Sm2_WIiiSo1sR45fquzwiC3AdxTRSG9bpqldcQ2EBE5Y/s1600/grafana.PNG\">\n <h3 style=\"padding-top:15px\">$grafana_version</h3>\n<div>"
   }
  },
  {
   "title": "Host CPU Count",
   "type": "stat",
   "description": "CPU Core count of Plex Server",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(cpu) (node_cpu_seconds_total{instance=\"192.168.0.13:9100\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Platform Version",
   "type": "stat",
   "description": "Platform and OS Version ",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "server_info",
     "legendFormat": "{{platform}} - {{platform_version}}"
    }
   ]
  },
  {
   "title": "Host Memory",
   "type": "stat",
   "description": "Amount of physical memory available",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (otel_system_memory_usage_bytes) / 1024 / 1024 - 400",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stream Counts",
   "type": "stat",
   "description": "Stream counts and transcodes for Plex Server",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(sum by(session) (rate(play_seconds_total{stream_type=~\"(transcode|directplay|DirectPlay)\"}[$__rate_interval]))) > 0) or vector(0)",
     "legendFormat": "Total Streams"
    },
    {
     "expr": "count( sum by (session) ( rate(play_seconds_total{stream_type=~\"(directplay|DirectPlay)\"}[$__rate_interval]) ) > 0 ) or on() vector(0)",
     "legendFormat": "Direct Play"
    },
    {
     "expr": "count( sum by (session) ( rate(play_seconds_total{stream_type=\"transcode\", transcode_type=~\"(video|both)\"}[$__rate_interval]) ) > 0 ) or on() vector(0)",
     "legendFormat": "Video Transcodes"
    },
    {
     "expr": "count( sum by (session) ( rate(play_seconds_total{stream_type=\"transcode\", transcode_type=~\"(audio|both)\"}[$__rate_interval]) ) > 0 ) or on() vector(0)",
     "legendFormat": "Audio Transcodes"
    },
    {
     "expr": "count( sum by (session) ( rate(play_seconds_total{subtitle_action=\"transcode\"}[$__rate_interval]) ) > 0 ) or on() vector(0)",
     "legendFormat": "Subtitle Transcodes"
    },
    {
     "expr": "count( sum by (session) ( rate(play_seconds_total{subtitle_action=\"burn\"}[$__rate_interval]) ) > 0 ) or on() vector(0)",
     "legendFormat": "Subtitle Burn"
    }
   ]
  },
  {
   "title": "Now playing (sessions)",
   "type": "table",
   "description": "Active stream sessions for Plex Server",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (user, device_type, device, stream_resolution, stream_file_resolution, server, stream_bitrate, stream_type, what) ((label_join(label_join(rate(play_seconds_total{media_type=\"episode\", stream_type!=\"\"}[45s]), \"what\", \" / \", \"title\", \"child_title\"), \"what\", \" / \", \"what\", \"grandchild_title\") or label_join(rate(play_seconds_total{media_type!=\"episode\", stream_type!=\"\"}[45s]), \"what\", \"\", \"title\"))) > 0"
    }
   ]
  },
  {
   "title": "Last 3 Series Added",
   "type": "table",
   "description": "The last 3 series added you can reduce or increase via transformations limit",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://192.168.0.205:8989/api/v3/series?",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Last Episode Added",
   "type": "table",
   "description": "Last episode added you can reduce or increase via transformations limit",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://192.168.0.205:8989/api/v3/series?",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Next Upcoming Episode",
   "type": "table",
   "description": "Next upcoming episodes you can reduce or increase via transformations limit",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://192.168.0.205:8989/api/v3/series?",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Last 3 Movies Added",
   "type": "table",
   "description": "The last 3 movies added you can reduce or increase via transformations limit",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://192.168.0.205:7878/api/v3/movie?",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Upcoming Movies for Download",
   "type": "table",
   "description": "Scheduled movies for download you can reduce or increase via transformations limit",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://192.168.0.205:7878/api/v3/movie?",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Total Media Counts",
   "type": "stat",
   "description": "Overview of all media counts",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "plex_media_movies", "legendFormat": "Movies" },
    { "expr": "plex_media_episodes", "legendFormat": "Episodes" },
    { "expr": "plex_media_music", "legendFormat": "Music" },
    { "expr": "plex_media_photos", "legendFormat": "Photos" },
    { "expr": "plex_media_other_videos", "legendFormat": "Home Movies" }
   ]
  },
  {
   "title": "Library Items",
   "type": "stat",
   "description": "Breakdown of library items ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(library) (plex_library_items)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Library Storage",
   "type": "stat",
   "description": "Breakdown of storage sizes for all libraries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(library) (library_storage_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Library Duration",
   "type": "stat",
   "description": "Library durations ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(library) (library_duration_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "gauge",
   "description": "Current CPU utilisation of Plex Server Host",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "host_cpu_util", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "gauge",
   "description": "Current memory utilisation of Plex Server Host",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "host_mem_util", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Download Speed",
   "type": "gauge",
   "description": "Download speed of your provider",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "download_speed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Network TX",
   "type": "gauge",
   "description": "Plex transmit bandwidth (bits/sec).",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "transmit_bytes_total / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Root Filesystem Used",
   "type": "gauge",
   "description": "Root filesystem usage ",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "otel_system_filesystem_usage_bytes{mountpoint=\"/\", state=\"used\"} - 2.024e+10",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "LaCie 4TB Used",
   "type": "gauge",
   "description": "Disk utilisation of LaCie 4TB",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "otel_system_filesystem_usage_bytes{mountpoint=\"/Volumes/LaCie 4TB\", state=\"used\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "LaCie 6TB Used",
   "type": "gauge",
   "description": "Disk utilisation of LaCie 6TB",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "otel_system_filesystem_usage_bytes{mountpoint=\"/Volumes/LaCie 6TB\", state=\"used\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LaCie 10TB Used",
   "type": "gauge",
   "description": "Disk utilisation of LaCie 10TB",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "otel_system_filesystem_usage_bytes{mountpoint=\"/Volumes/LaCie 10TB\", state=\"used\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "LaCie 16TB Usage",
   "type": "gauge",
   "description": "Disk utilisation LaCie 16TB",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "otel_system_filesystem_usage_bytes{mountpoint=\"/Volumes/LaCie 16TB\", state=\"used\"}",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}