{
 "title": "Plex Host Metrics",
 "description": "Host metrics dashboards for Mac M1/M2 Macs ",
 "tags": [
  "M1 Mac ",
  "M2 Mac Pro"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info{job!=\"node_exporter\"},job)"
    }
   },
   {
    "name": "nodename",
    "label": "Nodename",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, nodename)"
    }
   },
   {
    "name": "node",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\", nodename=\"$nodename\"}, instance)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   }
  ]
 },
 "panels": [
  { "title": "Quick CPU / Mem / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Overall CPU busy percentage (averaged across all cores)",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$node\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Sys Load",
   "type": "gauge",
   "description": "System load  over all CPU cores together",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(node_load1{instance=\"$node\",job=\"$job\"}) * 100 / count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Real RAM usage excluding cache and reclaimable memory",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_memory_active_bytes{job=\"$job\"}) / 1.6e+10 * 100"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Percentage of swap space currently used by the system",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (node_memory_swap_used_bytes{job=\"$job\"}) "
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (node_filesystem_size_bytes{instance=\"$node\", job=\"$job\", mountpoint=\"/\", fstype!=\"rootfs\"}\n   - node_filesystem_avail_bytes{instance=\"$node\", job=\"$job\", mountpoint=\"/\", fstype!=\"rootfs\"})\n  / node_filesystem_size_bytes{instance=\"$node\", job=\"$job\", mountpoint=\"/\", fstype!=\"rootfs\"}\n) * 100\n"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(cpu) (node_cpu_seconds_total{instance=\"$node\", job=\"$job\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host Memory",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (otel_system_memory_usage_bytes) / 1024 / 1024 - 400",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$node\",job=\"$job\"} - node_boot_time_seconds{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  { "title": "Basic CPU / Mem / Net / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "CPU time spent busy vs idle, split by activity type",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"system\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"user\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"iowait\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=~\".*irq\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\",  mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"idle\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Overview usage vs available",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(node_memory_active_bytes{job=\"$job\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Per-interface network traffic (receive and transmit) in bits per second",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "Rx {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "Tx {{device}} "
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "timeseries",
   "description": "Percentage of filesystem space used for each mounted device",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((node_filesystem_size_bytes{instance=\"$node\", job=\"$job\", device!~\"rootfs\"} - node_filesystem_avail_bytes{instance=\"$node\", job=\"$job\", device!~\"rootfs\"}) / node_filesystem_size_bytes{instance=\"$node\", job=\"$job\", device!~\"rootfs\"}) * 100",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "CPU / Memory / Net / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "CPU time usage split by state, normalized across all CPU cores",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"system\",instance=\"$node\",job=\"$job\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"user\",instance=\"$node\",job=\"$job\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"nice\",instance=\"$node\",job=\"$job\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Nice - Niced processes executing in user mode"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"iowait\",instance=\"$node\",job=\"$job\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"irq\",instance=\"$node\",job=\"$job\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Irq - Servicing interrupts"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"softirq\",instance=\"$node\",job=\"$job\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Softirq - Servicing softirqs"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"steal\",instance=\"$node\",job=\"$job\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"idle\",instance=\"$node\",job=\"$job\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Idle - Waiting for something to happen"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_guest_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval]))) > 0",
     "legendFormat": "Guest CPU usage"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Breakdown of physical memory and swap usage. Hardware-detected memory errors are also displayed",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_total_bytes{instance=\"$node\",job=\"$job\"} - node_memory_free_bytes{instance=\"$node\",job=\"$job\"} - node_memory_swap_total_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_memory_free_bytes{job=\"$job\", instance=\"$nodename\"}",
     "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Unused - Free memory unassigned"
    },
    {
     "expr": "node_memory_swap_total_bytes{job=\"$job\", instance=\"$node\"}",
     "legendFormat": "Swap - Swap space used"
    }
   ]
  },
  {
   "title": "Paging  & Swap (Virtual Memory)",
   "type": "timeseries",
   "description": "Breakdown of total paging & swap activity",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 35 },
   "targets": [
    { "expr": "total_pageouts", "legendFormat": "Total PageOuts" },
    { "expr": "total_pageins", "legendFormat": "Total PageIns" },
    { "expr": "total_swapins", "legendFormat": "Total SwapIns" },
    { "expr": "total_swapouts", "legendFormat": "Total SwapOuts" },
    { "expr": "total_pages_active", "legendFormat": "Total Active Pages" },
    { "expr": "total_pages_free", "legendFormat": "Total Pages Free" }
   ]
  },
  {
   "title": "Network Saturation",
   "type": "timeseries",
   "description": "Network interface utilization as a percentage of its maximum capacity",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"$job\"}[$__rate_interval]) / 1000",
     "legendFormat": "{{device}} - Rx in"
    },
    {
     "expr": "(rate(node_network_transmit_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])\n / ignoring(speed) node_network_speed_bytes{instance=\"$node\",job=\"$job\", speed!=\"-1\"}) * 100",
     "legendFormat": "{{device}} - Tx out"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "description": "Incoming and outgoing network traffic per interface",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Rx in"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Tx out"
    }
   ]
  },
  {
   "title": "Total Network Throughput",
   "type": "timeseries",
   "description": "Total amount of network throughput (all interfaces) since the last reboot",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "network_out_total_bytes_per_second",
     "legendFormat": "Network Out (total bytes)"
    },
    {
     "expr": "network_in_total_bytes_per_second",
     "legendFormat": "Network In (total bytes)"
    }
   ]
  },
  {
   "title": "Disk IOps",
   "type": "timeseries",
   "description": "Disk I/O operations per second for each device",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Write"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "timeseries",
   "description": "Disk I/O throughput per device",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Write"
    }
   ]
  },
  {
   "title": "Filesystem Space Available",
   "type": "timeseries",
   "description": "Amount of available disk space per mounted filesystem, excluding rootfs. Based on block availability to non-root users",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{job=\"$job\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Filesystem Used",
   "type": "timeseries",
   "description": "Disk usage (used = total - available) per mountpoint",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'} - node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk I/O Utilization",
   "type": "timeseries",
   "description": "Percentage of time the disk was actively processing I/O operations",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(otel_system_disk_io_time_seconds_total{job=\"otel-plex-collector\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Total Disk IOPS read/write per second",
   "type": "timeseries",
   "description": "Total amount of time in seconds disks were actively processing I/O operations",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "disk_write_total_iops_per_second",
     "legendFormat": "Total Disk IOPS write per second"
    },
    {
     "expr": "disk_read_total_iops_per_second",
     "legendFormat": "Total Disk IOPS read per second"
    }
   ]
  },
  { "title": "System Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "Processes Status",
   "type": "timeseries",
   "description": "Running tasks currently in runnable or blocked states. Helps identify CPU contention or I/O wait bottlenecks.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "otel_system_processes_count{status=\"running\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "otel_system_processes_count{status=\"blocked\"}",
     "legendFormat": "Blocked"
    },
    {
     "expr": "otel_system_processes_count{status=\"sleeping\"}",
     "legendFormat": "Sleeping"
    },
    {
     "expr": "otel_system_processes_count{status=\"zombies\"}",
     "legendFormat": "Zombie"
    },
    { "expr": "running_tasks", "legendFormat": "Running tasks" }
   ]
  },
  {
   "title": "Key Stack Process Details",
   "type": "timeseries",
   "description": "Key User% process information for media stack applications",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "radarr_proc_user{job=\"node_exporter_m1\"}",
     "legendFormat": "Radarr User (%)"
    },
    {
     "expr": "sonarr_proc_user{job=\"node_exporter_m1\"}",
     "legendFormat": "Sonarr User (%)"
    },
    { "expr": "plex_proc_user", "legendFormat": "Plex Media Server User (%)" },
    { "expr": "nzbget_proc_user", "legendFormat": "NZBGet User (%)" }
   ]
  },
  { "title": "System Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "System Load",
   "type": "timeseries",
   "description": "System load average over 1, 5, and 15 minutes. Reflects the number of active or waiting processes. Values above CPU core count may indicate overload",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Load 15m"
    },
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))",
     "legendFormat": "CPU Core Count"
    }
   ]
  },
  { "title": "Hardware Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 122 } },
  {
   "title": "Hardware Temperature Monitor",
   "type": "timeseries",
   "description": "Monitors hardware sensor temperatures and critical thresholds as exposed by Linux hwmon. Includes CPU, GPU, and motherboard sensors where available",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "cpu_temp{job=\"node_exporter_m1\"}",
     "legendFormat": "{{ chip_name }} {{ sensor }}"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "timeseries",
   "description": "Shows the online status of power supplies and consumption",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    { "expr": "gpu_power", "legendFormat": "GPU Power (online)" },
    { "expr": "cpu_power", "legendFormat": "CPU Power (online)" }
   ]
  },
  { "title": "Storage Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 133 } },
  {
   "title": "Disk Read/Write IOps",
   "type": "timeseries",
   "description": "Number of I/O operations completed per second for the device (after merges), including both reads and writes",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Write"
    }
   ]
  },
  {
   "title": "Disk Read/Write Data",
   "type": "timeseries",
   "description": "Number of bytes read from or written to the device per second",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Write"
    }
   ]
  },
  {
   "title": "Disk Average Wait Time",
   "type": "timeseries",
   "description": "Average time for requests issued to the device to be served. This includes the time spent by the requests in queue and the time spent servicing them.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval]) / irate(node_disk_reads_completed_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Read"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval]) / irate(node_disk_writes_completed_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Write"
    }
   ]
  },
  { "title": "Storage Filesystem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 156 } },
  {
   "title": "Filesystem in ReadOnly / Error",
   "type": "timeseries",
   "description": "Indicates filesystems mounted in read-only mode or reporting device-level I/O errors.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "node_filesystem_readonly{instance=\"$node\",job=\"$job\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}} - ReadOnly"
    },
    {
     "expr": "node_filesystem_device_error{instance=\"$node\",job=\"$job\",device!~'rootfs',fstype!~'tmpfs'}",
     "legendFormat": "{{mountpoint}} - Device error"
    }
   ]
  },
  {
   "title": "File Nodes Free",
   "type": "timeseries",
   "description": "Number of free file nodes (inodes) available per mounted filesystem. A low count may prevent file creation even if disk space is available",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filesystem_files_free{instance=\"$node\",job=\"$job\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "File Nodes Size",
   "type": "timeseries",
   "description": "Number of file nodes (inodes) available per mounted filesystem. Reflects maximum file capacity regardless of disk size",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "node_filesystem_files{instance=\"$node\",job=\"$job\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "Network Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 177 } },
  {
   "title": "Network Traffic by Packets",
   "type": "timeseries",
   "description": "Number of network packets received and transmitted per second, by interface.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_packets_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Rx in"
    },
    {
     "expr": "rate(node_network_transmit_packets_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Tx out"
    }
   ]
  },
  {
   "title": "Network Traffic Errors",
   "type": "timeseries",
   "description": "Rate of packet-level errors for each network interface. Receive errors may indicate physical or driver issues; transmit errors may reflect collisions or hardware faults",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_errs_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Rx in"
    },
    {
     "expr": "rate(node_network_transmit_errs_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Tx out"
    }
   ]
  },
  {
   "title": "Network Traffic Drop",
   "type": "timeseries",
   "description": "Rate of dropped packets per network interface. Receive drops can indicate buffer overflow or driver issues; transmit drops may result from outbound congestion or queuing limits",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 188 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_drop_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Rx in"
    },
    {
     "expr": "rate(node_network_transmit_drop_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Tx out"
    }
   ]
  },
  {
   "title": "Network Traffic Collision",
   "type": "timeseries",
   "description": "Rate of packet collisions detected during transmission. Mostly relevant on half-duplex or legacy Ethernet networks",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 188 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_colls_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Tx out"
    }
   ]
  },
  {
   "title": "Network Traffic Multicast",
   "type": "timeseries",
   "description": "Rate of incoming multicast packets received per network interface. Multicast is used by protocols such as mDNS, SSDP, and some streaming or cluster services",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 198 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_multicast_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Rx in"
    }
   ]
  },
  { "title": "Node Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 209 } },
  {
   "title": "Node Exporter Scrape Time",
   "type": "timeseries",
   "description": "Duration of each individual collector executed during a Node Exporter scrape. Useful for identifying slow or failing collectors",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 210 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_scrape_collector_duration_seconds{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{collector}}"
    }
   ]
  },
  {
   "title": "Exporter Process CPU Usage",
   "type": "timeseries",
   "description": "Rate of CPU time used by the process exposing this metric (user + system mode)",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 210 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total[$__rate_interval])",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "Exporter Processes Memory",
   "type": "timeseries",
   "description": "Tracks the memory usage of the process exposing this metric (e.g., node_exporter), including current virtual memory and maximum virtual memory limit",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 220 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "Virtual Memory" },
    {
     "expr": "process_virtual_memory_max_bytes",
     "legendFormat": "Virtual Memory Limit"
    }
   ]
  },
  {
   "title": "Exporter File Descriptor Usage",
   "type": "timeseries",
   "description": "Number of file descriptors used by the exporter process versus its configured limit",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 220 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_max_fds{job=\"$job\"}",
     "legendFormat": "Maximum open file descriptors"
    },
    { "expr": "process_open_fds", "legendFormat": "Open file descriptors" }
   ]
  },
  {
   "title": "Prometheus Storage (GB)",
   "type": "timeseries",
   "description": "Calculated Prometheus storage blocks in GB",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 230 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(prometheus_tsdb_storage_blocks_bytes{instance=\"localhost:9091\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Exporter Scrape",
   "type": "bargauge",
   "description": "Shows whether each Node Exporter collector scraped successfully (1 = success, 0 = failure), and whether the textfile collector returned an error.",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 230 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_scrape_collector_success{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{collector}}"
    },
    {
     "expr": "1 - node_textfile_scrape_error{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "textfile"
    }
   ]
  }
 ]
}